[package]
name = "SeismometerServer"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.5.1"
ctrlc = "3.4.5"
chrono = "0.4.38"
anyhow = "1.0.89"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"